navigate to prepopulated evaluate measure and care gaps page from specific resource pages
projecttacoma/deqm-test-server-frontend pull request #30
Opened 2022-08-11 13:10 UTC by djacoby04

## Summary
Renders evaluate measure and care gaps buttons on specific resource pages to redirect to evaluate or care gaps page for a given measure. The corresponding fields are then pre-populated with data from the original resource page.  

## New behavior
Patient, Practitioner and Group resources now contain an evaluate measure button, and Patient, Practitioner, and Organization resources now contain a care gaps button. When clicked, these buttons allow the user to select a measure from a dropdown menu and reroute to that measure's evaluate or care gaps page. The patient, practitioner, group, and organization field is populated based on the original resource.  

## Code changes
- **components/ResourceMenu.tsx**, menu component added that displays clickable measure resources that navigate to the specified page 
- ** pages/[resourceType]/[id]/care-gaps.tsx**, added functionality to retrieve patient, organization, and practitioner information from the URL to prepopulate select fields. 
- ** pages/[resourceType]/[id]/evaluate-measure.tsx**, added functionality to retrieve patient, group, and practitioner information from the URL to prepopulate select fields.
- ** pages/[resourceType]/[id]/index.tsx**, renders care gap menu buttons on patient, practitioner, and organization resources and evaluate measure buttons on patient, practitioner, and group. 
- - **__tests__/pages/resource/id/index.test.tsx**, unit tests added
- - **__tests__/pages/resource/id/evaluate.test.tsx**, unit tests added
- - **__tests__/pages/resource/id/care-gaps.test.tsx**, unit tests added
## Testing Guidance
- See the README.md for first time setup instructions.
#### Testing in browser: 
To start the frontend: `npm run dev` then navigate to http://localhost:3001 in a browser
- Navigate to any patient resource ID page. Click on the evaluate measure button and select any measure from the drop down. You should be redirected to that measure’s evaluate measure page and the patient field should be pre-populated with the patient data. Click calculate and verify that the patient appears in the report. 
- Repeat this process with the care gaps button on the patient page. 
- Navigate to any participant resource ID page and repeat this process with the care gaps and evaluate measure buttons 
- Navigate to any group resource ID page and repeat this process with the evaluate measure button. Note that the care gaps button should not appear
- Navigate to any organization resource ID page and repeat this process with the care gaps button. Note that the evaluate measure button should not appear
#### Unit testing: 
- Run the unit tests: `npm run test`

2022-08-11 17:22 UTC, sarahmcdougall requested changes
This new functionality is super convenient! :) Aside from the in-line comments, I have a few other things that I noticed (that may or may not warrant changes depending on your opinions/other reviewer opinions):

- I tested with all the measures from the `upload-bundles` script in `deqm-test-server` and most of the measure names get cut off in the measure resource menu. When demoing to people who aren't on the dev team, it might be useful to have the whole name displayed. Maybe we can consider expanding the size of the menu or adding ellipses when the name is too long.
<img width="237" alt="Screen Shot 2022-08-11 at 1 20 01 PM" src="https://user-images.githubusercontent.com/87094479/184194743-fdf13e5e-011b-4dd8-9f79-3d0be6899033.png">


- This one isn't that big of a deal and can be fixed in a future PR if we want, but, for example, if we select a Patient from the Patient resource page and then click on "Evaluate Measure," we are brought to the evaluate measure page with the "subject" select component populated with the Patient. If we change the radio button to be a "population" report instead of "subject," and then we change it back to "subject," we lose that subject that we selected from the Patient resource page. I'm not sure if it's worth changing up the `useEffects` so that we keep the value there in case someone accidentally changes the radio button and then wants to go back. I think it would be convenient, but then again, the user can always just use the select component to select a subject again.
- For gaps in care, if we select an organization and navigate to care gaps, the radio value automatically gets set to "Organization." However, if we select a practitioner and navigate to care gaps, the radio value stays at "Subject." Since a practitioner can only be provided in conjunction with an organization (and not with a subject), we should consider changing this radio value to "Organization" when we select a practitioner.

2022-08-12 19:44 UTC, mgramigna commented on components/ResourceMenu.tsx
> +  measureArray: (fhirJson.BundleEntry | null)[] | undefined;
Maybe we should rename this prop since this component is general for any resource type, not just measures?

2022-08-12 19:44 UTC, mgramigna commented on components/ResourceMenu.tsx
> +            <Menu.Item> something went wrong </Menu.Item>
Maybe we can change this to like "no available options" or something

2022-08-12 20:08 UTC, mgramigna approved these changes

2022-08-12 20:18 UTC, sarahmcdougall approved these changes
Great work!!!!!

2022-08-12 20:22 UTC, merged